name: model_finder_flutter
description: Flutter UI for ComfyUI Model Finder

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  path: ^1.8.3
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  json_annotation: ^4.8.1
  intl: ^0.18.1
  file_picker: ^6.2.1
  url_launcher: ^6.3.1
  flutter_markdown: ^0.6.23
  desktop_drop: ^0.4.4
  cross_file: ^0.3.3
  meta: ^1.10.0
  path_provider: ^2.1.2
  bitsdojo_window: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-VariableFont_wght.ttf 